services:
  cgit:
    image: ghcr.io/a1c7e0/cgit-docker:latest
    restart: unless-stopped
    ports:
      - "8090:80"
      - "2222:2222"
    volumes:
      - ./repos:/var/lib/git
      - ./secrets:/secrets
      - ./cgitrc:/etc/cgitrc:ro
